name: Build Experimental Image
on:
  workflow_dispatch:
jobs:
  audioserve-build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build image
        run: docker build --tag audioserve:debug --build-arg CARGO_RELEASE="" .
      # - name: Publish image
      #   run: |
      #     docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      #     docker push izderadicka/audioserve:experimental
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: |
          docker push ghcr.io/nebula-it/audioserve:debug
